[workspace]
members = ["crates/*"]
resolver = "2"

[package]
name = "blockchain_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
env_logger = "0.11"
hex = "0.4.3"
log = "0.4.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10.9"
