[package]
name = "p2p"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bincode = "1"
bytes = "1.11.0"
ed25519-dalek = { version = "2.2.0", features = ["digest"] }
hex = "0.4.3"
serde = "1.0.228"
sha2 = "0.10.9"
